#' import_SurvNet
#'
#' @return A data frame specified columns (hardcoded for now)
#'
#' @export
#'
#' @examples
#' import_SurvNet()
#'
#'
import_SurvNet <- function(){
  dsn <- odbcListDataSources()$name
  if (length(dsn) != 1) {
    if (length(dsn) > 1) {
      stop(paste("Multiple potential SurvNet data sources detected.",
                 "Please select one of:", paste(dsn, collapse = ", ")))
    } else {
      stop("No data source detected. Please configure ODBC.")
    }
  }
  # Connect if exactly one DSN is found
  myconn <- dbConnect(odbc(), dsn = dsn)
  # Try running the query and ensure the connection is closed
  data <- tryCatch({
    dbGetQuery(myconn,
               "SELECT DISTINCT [Data].[Version].[Token] AS 'Aktenzeichen' ,(SELECT I.ItemName FROM Meta.Catalogue2Item AS C2I INNER JOIN Meta.Item AS I ON C2I.IdItem = I.IdItem WHERE C2I.IdCatalogue = 1010 AND I.IdIndex = [Data].[Disease71].[ReportingCounty]) AS 'Meldelandkreis' ,[Data].[Disease71].[IdVersion], [Data].[Version].[IdType], [Data].[Version].[CodeRecordOwner] AS 'Eigentuemer', [Data].[Version].[IdRecord] AS 'IdRecord', [Data].[Disease71].[Sex] 'Geschlecht' , [Data].[Disease71].[ReportingDate] AS 'Meldedatum' , [Data].[Disease71].[MunicipalityKey] , [Data].[Disease71].[AgeComputed] , [Data].[Disease71].[StatusHospitalization] AS 'HospitalisierungStatus' , [Data].[Disease71].[StatusDeceased] AS 'VerstorbenStatus' ,ExPOI2.ExpKont1, ExPOI2.ExpSubKont1, ExPOI2.ExpLand1, ExPOI2.ExpBL1, ExPOI2.ExpLK1, ExPOI2.ExpKont2, ExOutInfo.AusbruchInfo_InterneRef FROM [Data].[Version] INNER JOIN [Data].[Disease71] ON [Data].[Version].[IdVersion] = [Data].[Disease71].[IdVersion] LEFT OUTER JOIN [Meta].[DayTable] DT1001 ON DT1001.IdDaySQL = CAST(CAST([Data].[Disease71].[ReportingDate] AS FLOAT) AS INT) LEFT OUTER JOIN [Meta].[DayTable] DT1110 ON DT1110.IdDaySQL = CAST(CAST([Data].[Disease71].[OnsetOfDisease] AS FLOAT) AS INT) Outer Apply Data.ExpandWithPlaceOfInfections2(Data.Version.IdVersion) ExPOI2 Outer Apply Data.ExpandWithOutbreakInfo ([Data].[Version].[IdVersion]) ExOutInfo WHERE (GETDATE() BETWEEN [Data].[Version].[ValidFrom] AND [Data].[Version].[ValidUntil]) AND ([Data].[Version].[IsActive] = 1) AND ([Data].[Version].[IdRecordType] = 1) AND (([Data].[Version].[IdType] IN (121,157,179,140,138))) AND (((DT1001.WeekYear>=2023)))")
  },
  error = function(e) {
    message("Error: Failed to execute the SQL query. Check your syntax and connection.")
    message("Details: ", e$message)
    return(NULL)  # Return NULL if an error occurs
  },
  finally = {
    dbDisconnect(myconn)
  })
  return(data)
}


#' .combine_exposure
#'
#' @param data Usually a tibble generated by \code{\link{import_SurvNet()}}
#'
#' @return A tibble derived the
#' tibble as generated by \code{\link{import_SurvNet()}}, but with
#' Expositionsort standardized
#'
.combine_exposure <- function(data){
  # function starting with ".", only used internally
  # Expositionsort: Combine information from multiple exposure variables into one
  dplyr::mutate(data,
    Expositionsort = case_when(
      !is.na(ExpKont2) ~ "mehrere Orte",
      !is.na(ExpLK1) & ExpBL1 == "Rheinland-Pfalz" ~ as.character(ExpLK1),
      !is.na(ExpBL1) & ExpLand1 == "Deutschland" ~ as.character(ExpBL1),
      !is.na(ExpLand1) ~ as.character(ExpLand1),
      !is.na(ExpSubKont1) ~ as.character(ExpSubKont1),
      !is.na(ExpKont1) ~ as.character(ExpKont1),
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(-ExpKont1:-ExpKont2)  # Remove columns from ExpKont1 to ExpKont2
}


#' .append_LK_LatLong
#'
#' Internal function (not exported), adds the latitude and longitude of the
#' centroid of each Landkreis, see \code{\link{LKLatLong}}
#'
#' @param data Usually a tibble generated by \code{\link{import_SurvNet()}}
#'
#' @return a tibble as generated by \code{\link{import_SurvNet()}}, but with
#' centroids (latitude and longitude) of the Landkreis included
#'
.append_LK_LatLong <- function(data){
  left_join(data, LKLatLong, by = "Meldelandkreis")
}

#' .append_GA_Kuerzel
#'
#' Internal function (not exported) to add the ID (Kuerzel) of the
#' Gesundheitsamt of a particular Landkries (LK)
#'
#' @param data Usually a tibble generated by \code{\link{import_SurvNet()}}
#'
#' @return a tibble as generated by \code{\link{import_SurvNet()}}, but with
#' Meldelandkreis and their IDs included
.append_GA_Kuerzel <- function(data){
# Import codes (Kürzel) for Aktenzeichen and join
  inner_join(data, Eigentuemer, by = "Eigentuemer") %>%
    rename(AZ = Aktenzeichen) %>%
    mutate(Aktenzeichen = gsub(" ", "", paste0(Kürzel, AZ)))
}


# ## Only the final cleanup missing

# # Final dataset with cleaned and formatted variables
# EpiDaten <- data4 %>%
#   mutate(
#     Meldedatum = as.Date(Meldedatum),
#     Outbreak = ifelse(!is.na(AusbruchInfo_InterneRef), 1, 0),
#     Hospitalization = recode(HospitalisierungStatus,
#                              "10" = "no", "20" = "yes", "-1" = "unknown", "0" = "not assessed"),
#     Deceased = recode(VerstorbenStatus,
#                       "10" = "no", "20" = "yes", "-1" = "unknown", "0" = "not assessed"),
#     `Host Sex` = recode(Geschlecht,
#                         "1" = "male", "2" = "female", "3" = "non-binary", "-1" = "unknown", "0" = "unknown"),
#     `Country of Isolation` = "Germany"
#   ) %>%
#   rename(
#     `Collection Date` = Meldedatum,
#     `Collected By` = Gesundheitsamt,
#     `Host Age` = AgeComputed
#   ) %>%
#   select(
#     Aktenzeichen, IdRecord, `Collection Date`, `Collected By`, Meldelandkreis,
#     MunicipalityKey, `Host Age`, `Host Sex`, Hospitalization, Deceased,
#     Expositionsort, Outbreak, `Country of Isolation`, `Lat/Long of Isolation`
#   )

